### ISSUE TITLE
Non SemVer jar files are renamed badly when copying into the distribution dir

### ISSUE THREAD

**Issue by quotidian-ennui** [adaptris/interlok-build-parent#75]
# Expected Behaviour

Jar files are renamed into the distribution directory without their version number.

# Actual Behaviour

If you have a dependency that doesn't conform (vaguely) to semantic versioning, then the jar rename that happens when copying jar files into the distribution directory are renamed to be `XXX-version-SNAPSHOT.jar.jar` which doesn't stop things from working because of the dynamic way in which jars are loaded, but is obviously confusing.

# Steps to reproduce

## Shows the error.

Use : https://github.com/adaptris-labs/interlok-twilio-sms/tree/develop

Note that the releaseVersion=4-SNAPSHOT (i.e. the custom code is build into a jar called `interlok-twilio-sms-4-SNAPSHOT.jar`)

- `gradle assemble`
- If you check `build/libs` then the jar is named properly.
```
$ ls build/libs
interlok-twilio-sms-4-SNAPSHOT.jar
```
- If you check `build/distribution/lib` then interlok-twilio-sms is called `interlok-twilio-sms-4-SNAPSHOT.jar.jar`
```
$ ls build/distribution/lib/interlok-twilio*.jar
build/distribution/lib/interlok-twilio-sms-4-SNAPSHOT.jar.jar
```

## Workaround the error

Use: https://github.com/adaptris-labs/interlok-twilio-sms/tree/build-parent-jar-rename-issue

Note that this sets the custom code version to be pinned against the `interlokVersion`; i.e. 4.3.0-RELEASE causes the jar file to be named `interlok-twilio-sms-4.3.0-SNAPSHOT.jar`

- `gradle assemble`
- If you check `build/libs` then the jar is named properly.
- If you check `build/distribution/lib` then interlok-twilio-sms is called `interlok-twilio-sms.jar`

**Comment by quotidian-ennui** [comment]
The logic that was applied for https://github.com/adaptris/interlok-build-parent/pull/48 and https://github.com/adaptris/interlok-build-parent/pull/49 is the cause of this issue.

It's not a critical situation where you are writing custom components inline with interlok config (since you're in control of the version) but becomes more of an issue if your corporate versioning convention doesn't match semantic versioning...

**Comment by sebastien-belin-adp** [comment]
This renaming is a bit of a pain. I'll raise a task in JIRA so we clearly have it in the backlog.
